name: LinuxRelease
on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    branches: [main]

jobs:
 linux-release-64:
    # Builds binaries for linux_amd64_gcc4
    name: Linux (x64)
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    env:
      EXTENSION_CONFIGS: '${GITHUB_WORKSPACE}/.github/config/bundled_extensions.cmake'
      ENABLE_EXTENSION_AUTOLOADING: 1
      ENABLE_EXTENSION_AUTOINSTALL: 1
      GEN: ninja
#      BUILD_BENCHMARK: 1
#      BUILD_ODBC: 1
      DEBUG_STACKTRACE: 1
      FORCE_WARN_UNUSED: 1
      DUCKDB_RUN_PARALLEL_CSV_TESTS: 1
      DISABLE_SANITIZER: 1

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: ./.github/actions/manylinux_2014_setup
      with:
        general: 1
        ninja-build: 1
        ccache: 1
        odbc: 1
        python_alias: 1

    - name: Install pytest
      run: |
        python3.7 -m pip install pytest

    - name: Build
      shell: bash
      run: make debug

    - name: Print platform
      shell: bash
      run: ./build/debug/duckdb -c "PRAGMA platform;"

    - name: Deploy
      shell: bash
      run: |
        zip -j duckdb_cli-linux-amd64.zip build/debug/duckdb

    - uses: actions/upload-artifact@v3
      with:
        name: duckdb-binaries-linux
        path: |
          duckdb_cli-linux-amd64.zip
